[package]
name = "messages"
version = "0.1.0"

[lib]
name = "messages"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
rules_account = { git = "https://github.com/ruleslabs/starknet-rules-account.git", branch = "main" }
